#live server configurations
#######################################
#   RTMP configurations(stand-alone)  #
#######################################
[rtmp]
enabled = true
port = 1935

######################################
#    HLS configurations              #
######################################
[hls]
enabled = true
port = 8080
record_path = "./record"

#######################################
#   LOG configurations                #
#######################################
[log]
level = "info"